# Generated by Django 5.1 on 2024-10-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moverspackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='user',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='briefitems',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='items',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='shiftingloc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
